-- MySQL Script generated by MySQL Workbench
-- Sat Sep  6 19:55:44 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema snapcash
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `snapcash` ;
CREATE SCHEMA IF NOT EXISTS `snapcash` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `snapcash` ;

-- -----------------------------------------------------
-- Table `snapcash`.`UserAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`UserAccount` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`UserAccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snapcash`.`PaymentInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`PaymentInfo` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`PaymentInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `provider` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snapcash`.`UserPaymentInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`UserPaymentInfo` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`UserPaymentInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UserAccount_id` INT NOT NULL,
  `PaymentInfo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UserBankInfo_BankInfo1_idx` (`PaymentInfo_id` ASC),
  UNIQUE INDEX `UserAccount_id_UNIQUE` (`UserAccount_id` ASC, `PaymentInfo_id` ASC),
  CONSTRAINT `fk_UserBankInfo_UserAccount`
    FOREIGN KEY (`UserAccount_id`)
    REFERENCES `snapcash`.`UserAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserBankInfo_BankInfo1`
    FOREIGN KEY (`PaymentInfo_id`)
    REFERENCES `snapcash`.`PaymentInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snapcash`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`Transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(12,2) NOT NULL,
  `sending_UserPaymentInfo_id` INT NOT NULL,
  `receiving_UserPaymentInfo_id` INT NOT NULL,
  `transaction_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transaction_UserBankInfo1_idx` (`sending_UserPaymentInfo_id` ASC),
  INDEX `fk_Transaction_UserBankInfo2_idx` (`receiving_UserPaymentInfo_id` ASC),
  CONSTRAINT `fk_Transaction_UserBankInfo1`
    FOREIGN KEY (`sending_UserPaymentInfo_id`)
    REFERENCES `snapcash`.`UserPaymentInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_UserBankInfo2`
    FOREIGN KEY (`receiving_UserPaymentInfo_id`)
    REFERENCES `snapcash`.`UserPaymentInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snapcash`.`TransactionAgent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`TransactionAgent` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`TransactionAgent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agent_UserPaymentInfo_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TransactionAgent_UserBankInfo1_idx` (`agent_UserPaymentInfo_id` ASC),
  INDEX `fk_TransactionAgent_Transaction1_idx` (`transaction_id` ASC),
  CONSTRAINT `fk_TransactionAgent_UserBankInfo1`
    FOREIGN KEY (`agent_UserPaymentInfo_id`)
    REFERENCES `snapcash`.`UserPaymentInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TransactionAgent_Transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `snapcash`.`Transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snapcash`.`Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snapcash`.`Friend` ;

CREATE TABLE IF NOT EXISTS `snapcash`.`Friend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  INDEX `fk_Friend_UserAccount1_idx` (`user_id` ASC),
  INDEX `fk_Friend_UserAccount2_idx` (`friend_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Friend_UserAccount1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snapcash`.`UserAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friend_UserAccount2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `snapcash`.`UserAccount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
